### ISSUE TITLE
question about training optimizer

### ISSUE THREAD

**Issue by 2857451652** [jzenn/Image-AutoEncoder#1]
Hello, I really appriciate your code. It helps me a lot.
But I have a question about the optimizer in the training process. I don't understand why "only optimize the decoder in the model"? Is the encoder already trained?

**Comment by jzenn** [comment]
Hi, thank you for your interest! I used this AutoEncoder model in a project where I was only training the decoder model. In fact, the method `get_encoder_decoder_model` loads a pre-trained encoder model from `configuration['encoder_model_path']`. 

If you don't want to load a pre-trained model, you can just comment out those lines, i.e.:
```
    # encoder_model_path = configuration['encoder_model_path']
    # print('using the encoder from {}'.format(encoder_model_path))

    # checkpoint = torch.load(encoder_model_path, map_location='cpu')
    # print('loaded checkpoint')

    encoder = Encoder()
    print('got encoder model')
    # encoder.load_state_dict(checkpoint)
    # print('loaded encoder checkpoint')

    # for param in encoder.parameters():
    #     param.requires_grad = False
```

Additionally, you have to change the optimizer, in order to train the parameters of the encoder as well as the decoder:
```
    # only optimize the decoder in the model (!)
    try:
        # optimizer = optim.Adam(encoder_decoder_model.decoder.parameters(), lr=configuration['lr'])
        optimizer = optim.Adam(encoder_decoder_model.parameters(), lr=configuration['lr'])
    except:
        # optimizer = optim.Adam(encoder_decoder_model.module.decoder.parameters(), lr=configuration['lr'])
        optimizer = optim.Adam(encoder_decoder_model.module.parameters(), lr=configuration['lr'])
    print('got optimizer')
```

I hope this answer clarifies your question.

**Comment by 2857451652** [comment]
Thanks a lot! It totally solved my problem. ^^
